---
- name: "{{ konductor.plugin }} | command:cmd.grub | Configure Libvirtd"
  command:
    cmd: |
      grubby --args={{ item }} --update-kernel=ALL
  with_items:
    - "{{ grub.RedHat8 }}"

- name: "{{ konductor.plugin }} | reboot:timeout.600s | Rebooting Host"
  reboot:
    msg: "Restarting host for kernel arguments to take effect"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: whoami
  when:
    - reboot
