---
- name: '{{ konductor.plugin }} | Build OpenShift install-config.yml'
  import_role: sparta.collector.dependencies

- name: '{{ konductor.plugin }} | Build OpenShift install-config.yml'
  template: 
    src: libvirt-install-config.yaml.j2
    dest: "{{ dir.install_config }}/undercloud-{{ item }}"
  with_items:
    - "{{ dir.install_config }}"
    - "{{ dir.manifests }}"

- name: Create OCP manifests
  shell:
    chdir: "{{ dir.manifests }}"
    cmd: "{{ dir.manifests }}/openshift-install create manifests --dir {{ dir.manifests }}"

# Separate partition for ETCD for better performance
# name: Process machine config for disk partitioning
# template: 
#   src: 98-etcd-partition.yaml
#   dest: "{{ ocp_install_dir }}/manifests"
# when: platform == "O^3"
