---
- name: Install OCS
  environment:
    KUBECONFIG: "{{ dir.kubeconfig }}/undercloud.config"
  roles:
    - role: openshift-ocs-install
      when: ocs_install == True
  tags:
    - openshift-ocs-install

# - name: Create network bridge
#   hosts: localhost
#   connection: local
#   environment:
#     KUBECONFIG: "{{ cluster_kubeconfig }}"
#   roles:
#     - openshift-create-bridge
#   tags:
#     - openshift-create-bridge

# - name: Add HTPasswd auth provider
#   hosts: localhost
#   connection: local
#   environment:
#     KUBECONFIG: "{{ cluster_kubeconfig }}"
#   roles:
#     - openshift-auth-provider
#   tags:
#     - openshift-auth-provider

# - name: Install OpenShift Virtualization
#   hosts: localhost
#   connection: local
#   environment:
#     KUBECONFIG: "{{ cluster_kubeconfig }}"
#   roles:
#     - openshift-virt-install
#   tags:
#     - openshift-virt-install
