---
- name: '{{ konductor.plugin }} | Purge OpenShift Manifest Staging Area'
  file:
    state: absent
    path: "{{ item }}"
  with_items:
    - '{{ dir.config }}'
    - '{{ dir.ignition }}'
    - '{{ dir.manifests }}'

- name: '{{ konductor.plugin }} | Create OpenShift Manifest Staging Directory'
  file:
    state: directory
    path: "{{ item }}"
    mode: '0644'
  with_items:
    - '{{ dir.config }}'
    - '{{ dir.ignition }}'
    - '{{ dir.manifests }}'

