---
- name: "{{ konductor.plugin }} | nmcli:type.bridge | Create cluster bridge"
  community.general.nmcli:
    type: bridge
    state: present
    conn_name: Bridge_Qubo_O3
    ifname: qubo-br0
    stp: yes

- name: "{{ konductor.plugin }} | nmcli:type.bridge-slave | Attach interface to bridge"
  community.general.nmcli:
    state: present
    type: 'bridge-slave'
    conn_name: qubo-tenant-bridge-slave
    ifname: "{{ tenant_iface }}"
    master: qubo-br0
  when:
    - tenant_iface is defined and tenant_iface != "" and tenant_iface != "null"
